### ISSUE TITLE
Error during autotest

### ISSUE THREAD

**Issue by leonidasv** [sylvainlehmann/s3ql#3]
I'm getting this error when trying to test the build. I've already removed the MANIFEST.in file, still getting the same warning message.

```
root@machine-comp-01:~/s3ql# python3 -m pytest tests/
========================================== test session starts ==========================================
platform linux -- Python 3.5.2, pytest-3.1.1, py-1.4.34, pluggy-0.4.0 -- /usr/bin/python3
cachedir: tests/.cache
rootdir: /root/s3ql/tests, inifile: pytest.ini
plugins: catchlog-1.2.2
collected 279 items 

tests/t1_backends.py::test_read_write[local/aes] PASSED
tests/t1_backends.py::test_read_write[mock-s3c/aes] PASSED
tests/t1_backends.py::test_read_write[mock-gs/aes] PASSED
tests/t1_backends.py::test_read_write[local/aes+zlib] PASSED
tests/t1_backends.py::test_read_write[mock-s3c/aes+zlib] PASSED
tests/t1_backends.py::test_read_write[mock-gs/aes+zlib] PASSED
tests/t1_backends.py::test_read_write[local/plain] PASSED
tests/t1_backends.py::test_read_write[mock-s3c/plain] PASSED
tests/t1_backends.py::test_read_write[mock-gs/plain] PASSED
tests/t1_backends.py::test_read_write[local/zlib] PASSED
tests/t1_backends.py::test_read_write[mock-s3c/zlib] PASSED
tests/t1_backends.py::test_read_write[mock-gs/zlib] PASSED
tests/t1_backends.py::test_read_write[local/bzip2] PASSED
tests/t1_backends.py::test_read_write[mock-s3c/bzip2] PASSED
tests/t1_backends.py::test_read_write[mock-gs/bzip2] PASSED
tests/t1_backends.py::test_read_write[local/lzma] PASSED
tests/t1_backends.py::test_read_write[mock-s3c/lzma] PASSED
tests/t1_backends.py::test_read_write[mock-gs/lzma] PASSED
tests/t1_backends.py::test_read_write[local/raw] PASSED
tests/t1_backends.py::test_read_write[mock-s3c/raw] PASSED
tests/t1_backends.py::test_read_write[mock-gs/raw] PASSED
tests/t1_backends.py::test_issue114[backend0] SKIPPED
tests/t1_backends.py::test_complex_meta[local/raw] PASSED
tests/t1_backends.py::test_complex_meta[mock-s3c/raw] PASSED
tests/t1_backends.py::test_complex_meta[mock-gs/raw] PASSED
tests/t1_backends.py::test_complex_meta[local/plain] PASSED
tests/t1_backends.py::test_complex_meta[local/aes] PASSED
tests/t1_backends.py::test_complex_meta[local/zlib] PASSED
tests/t1_backends.py::test_list[local/aes] PASSED
tests/t1_backends.py::test_list[mock-s3c/aes] PASSED
tests/t1_backends.py::test_list[mock-gs/aes] PASSED
tests/t1_backends.py::test_readslowly[local/raw] PASSED
tests/t1_backends.py::test_readslowly[mock-s3c/raw] PASSED
tests/t1_backends.py::test_readslowly[mock-gs/raw] PASSED
tests/t1_backends.py::test_readslowly[local/plain] PASSED
tests/t1_backends.py::test_readslowly[local/aes] PASSED
tests/t1_backends.py::test_readslowly[local/zlib] PASSED
tests/t1_backends.py::test_readslowly[local/aes+zlib] PASSED
tests/t1_backends.py::test_delete[local/aes] PASSED
tests/t1_backends.py::test_delete[mock-s3c/aes] PASSED
tests/t1_backends.py::test_delete[mock-gs/aes] PASSED
tests/t1_backends.py::test_delete_multi[local/aes] PASSED
tests/t1_backends.py::test_delete_multi[mock-s3c/aes] PASSED
tests/t1_backends.py::test_delete_multi[mock-gs/aes] PASSED
tests/t1_backends.py::test_clear[local/aes] PASSED
tests/t1_backends.py::test_clear[mock-s3c/aes] PASSED
tests/t1_backends.py::test_clear[mock-gs/aes] PASSED
tests/t1_backends.py::test_copy[local/raw] PASSED
tests/t1_backends.py::test_copy[mock-s3c/raw] PASSED
tests/t1_backends.py::test_copy[mock-gs/raw] PASSED
tests/t1_backends.py::test_copy[local/plain] PASSED
tests/t1_backends.py::test_copy[local/aes] PASSED
tests/t1_backends.py::test_copy[local/zlib] PASSED
tests/t1_backends.py::test_copy_special[local/raw] PASSED
tests/t1_backends.py::test_copy_special[mock-s3c/raw] PASSED
tests/t1_backends.py::test_copy_special[mock-gs/raw] PASSED
tests/t1_backends.py::test_copy_newmeta[local/raw] PASSED
tests/t1_backends.py::test_copy_newmeta[mock-s3c/raw] PASSED
tests/t1_backends.py::test_copy_newmeta[mock-gs/raw] PASSED
tests/t1_backends.py::test_copy_newmeta[local/aes] PASSED
tests/t1_backends.py::test_copy_newmeta[local/zlib] PASSED
tests/t1_backends.py::test_rename[local/raw] PASSED
tests/t1_backends.py::test_rename[mock-s3c/raw] PASSED
tests/t1_backends.py::test_rename[mock-gs/raw] PASSED
tests/t1_backends.py::test_rename[local/aes] PASSED
tests/t1_backends.py::test_rename[local/zlib] PASSED
tests/t1_backends.py::test_rename_newmeta[local/raw] PASSED
tests/t1_backends.py::test_rename_newmeta[mock-s3c/raw] PASSED
tests/t1_backends.py::test_rename_newmeta[mock-gs/raw] PASSED
tests/t1_backends.py::test_rename_newmeta[local/aes] PASSED
tests/t1_backends.py::test_rename_newmeta[local/zlib] PASSED
tests/t1_backends.py::test_update_meta[local/raw] PASSED
tests/t1_backends.py::test_update_meta[mock-s3c/raw] PASSED
tests/t1_backends.py::test_update_meta[mock-gs/raw] PASSED
tests/t1_backends.py::test_update_meta[local/aes] PASSED
tests/t1_backends.py::test_update_meta[local/zlib] PASSED
tests/t1_backends.py::test_copy_error[mock-s3c/raw] PASSED
tests/t1_backends.py::test_copy_error[mock-s3c/aes] PASSED
tests/t1_backends.py::test_copy_error[mock-s3c/zlib] PASSED
tests/t1_backends.py::test_corruption[local/aes] PASSED
tests/t1_backends.py::test_corruption[local/aes+zlib] PASSED
tests/t1_backends.py::test_corruption[local/zlib] PASSED
tests/t1_backends.py::test_corruption[local/bzip2] PASSED
tests/t1_backends.py::test_corruption[local/lzma] PASSED
tests/t1_backends.py::test_extra_data[local/aes] PASSED
tests/t1_backends.py::test_extra_data[local/aes+zlib] PASSED
tests/t1_backends.py::test_extra_data[local/zlib] PASSED
tests/t1_backends.py::test_extra_data[local/bzip2] PASSED
tests/t1_backends.py::test_extra_data[local/lzma] PASSED
tests/t1_backends.py::test_multi_packet[local/raw] PASSED
tests/t1_backends.py::test_multi_packet[mock-s3c/raw] PASSED
tests/t1_backends.py::test_multi_packet[mock-gs/raw] PASSED
tests/t1_backends.py::test_multi_packet[local/plain] PASSED
tests/t1_backends.py::test_multi_packet[mock-s3c/plain] PASSED
tests/t1_backends.py::test_multi_packet[mock-gs/plain] PASSED
tests/t1_backends.py::test_multi_packet[local/aes] PASSED
tests/t1_backends.py::test_multi_packet[mock-s3c/aes] PASSED
tests/t1_backends.py::test_multi_packet[mock-gs/aes] PASSED
tests/t1_backends.py::test_multi_packet[local/aes+zlib] PASSED
tests/t1_backends.py::test_multi_packet[mock-s3c/aes+zlib] PASSED
tests/t1_backends.py::test_multi_packet[mock-gs/aes+zlib] PASSED
tests/t1_backends.py::test_multi_packet[local/zlib] PASSED
tests/t1_backends.py::test_multi_packet[mock-s3c/zlib] PASSED
tests/t1_backends.py::test_multi_packet[mock-gs/zlib] PASSED
tests/t1_backends.py::test_issue431[local/raw] PASSED
tests/t1_backends.py::test_issue431[local/plain] PASSED
tests/t1_backends.py::test_issue431[local/aes] PASSED
tests/t1_backends.py::test_issue431[local/aes+zlib] PASSED
tests/t1_backends.py::test_issue431[local/zlib] PASSED
tests/t1_backends.py::test_encryption[local/aes] PASSED
tests/t1_backends.py::test_encryption[local/aes+zlib] PASSED
tests/t1_backends.py::test_replay[local/aes] PASSED
tests/t1_backends.py::test_replay[local/aes+zlib] PASSED
tests/t1_backends.py::test_list_bug[mock-s3c/raw] PASSED
tests/t1_backends.py::test_corrupted_get[mock-s3c/aes+zlib] PASSED
tests/t1_backends.py::test_corrupted_meta[mock-s3c/raw] PASSED
tests/t1_backends.py::test_corrupted_meta[mock-s3c/aes+zlib] PASSED
tests/t1_backends.py::test_corrupted_put[mock-s3c/raw] PASSED
tests/t1_backends.py::test_corrupted_put[mock-s3c/aes+zlib] PASSED
tests/t1_backends.py::test_get_s3error[mock-s3c/raw] PASSED
tests/t1_backends.py::test_get_s3error[mock-s3c/aes+zlib] PASSED
tests/t1_backends.py::test_head_s3error[mock-s3c/raw] PASSED
tests/t1_backends.py::test_head_s3error[mock-s3c/aes+zlib] PASSED
tests/t1_backends.py::test_delete_s3error[mock-s3c/raw] PASSED
tests/t1_backends.py::test_backoff[mock-s3c/raw] PASSED
tests/t1_backends.py::test_httperror[mock-s3c/raw] PASSED
tests/t1_backends.py::test_put_s3error_early[mock-s3c/raw] PASSED
tests/t1_backends.py::test_put_s3error_early[mock-s3c/aes+zlib] PASSED
tests/t1_backends.py::test_put_s3error_med[mock-s3c/raw] PASSED
tests/t1_backends.py::test_put_s3error_med[mock-s3c/aes+zlib] PASSED
tests/t1_backends.py::test_put_s3error_late[mock-s3c/raw] PASSED
tests/t1_backends.py::test_put_s3error_late[mock-s3c/aes+zlib] PASSED
tests/t1_backends.py::test_issue58[mock-s3c/raw] PASSED
tests/t1_backends.py::test_issue58[mock-s3c/aes+zlib] PASSED
tests/t1_backends.py::test_issue58_b[mock-s3c/raw] PASSED
tests/t1_backends.py::test_issue58_b[mock-s3c/aes+zlib] PASSED
tests/t1_backends.py::test_expired_token_get[mock-gs/raw] PASSED
tests/t1_backends.py::test_expired_token_get[mock-gs/aes+zlib] PASSED
tests/t1_backends.py::test_expired_token_put[mock-gs/raw] PASSED
tests/t1_backends.py::test_expired_token_put[mock-gs/aes+zlib] PASSED
tests/t1_backends.py::test_conn_abort[mock-s3c/raw] PASSED
tests/t1_backends.py::test_conn_abort[mock-s3c/aes+zlib] PASSED
tests/t1_dump.py::DumpTests::test_1_vals_1 PASSED
tests/t1_dump.py::DumpTests::test_1_vals_2 PASSED
tests/t1_dump.py::DumpTests::test_1_vals_3 PASSED
tests/t1_dump.py::DumpTests::test_2_buf_auto PASSED
tests/t1_dump.py::DumpTests::test_2_buf_fixed PASSED
tests/t1_dump.py::DumpTests::test_3_deltas_1 PASSED
tests/t1_dump.py::DumpTests::test_3_deltas_2 PASSED
tests/t1_dump.py::DumpTests::test_3_deltas_3 PASSED
tests/t1_dump.py::DumpTests::test_4_time PASSED
tests/t1_dump.py::DumpTests::test_5_multi PASSED
tests/t1_dump.py::DumpTests::test_transactions PASSED
tests/t1_retry.py::test_retry PASSED
tests/t1_retry.py::test_retry_generator PASSED
tests/t1_retry.py::test_is_retry PASSED
tests/t1_retry.py::test_logging PASSED
tests/t1_serialization.py::test_simple PASSED
tests/t1_serialization.py::test_wrong_key PASSED
tests/t1_serialization.py::test_cmplx_value PASSED
tests/t1_serialization.py::test_thaw_errors PASSED
tests/t1_serialization.py::test_checksum PASSED
tests/t2_block_cache.py::cache_tests::test_expire PASSED
tests/t2_block_cache.py::cache_tests::test_expire_race PASSED
tests/t2_block_cache.py::cache_tests::test_get PASSED
tests/t2_block_cache.py::cache_tests::test_parallel_expire PASSED
tests/t2_block_cache.py::cache_tests::test_remove_cache PASSED
tests/t2_block_cache.py::cache_tests::test_remove_cache_db PASSED
tests/t2_block_cache.py::cache_tests::test_remove_db PASSED
tests/t2_block_cache.py::cache_tests::test_remove_referenced PASSED
tests/t2_block_cache.py::cache_tests::test_thread_hang PASSED
tests/t2_block_cache.py::cache_tests::test_upload PASSED
tests/t2_block_cache.py::cache_tests::test_upload_race PASSED
tests/t3_fs_api.py::fs_api_tests::test_copy_tree PASSED
tests/t3_fs_api.py::fs_api_tests::test_copy_tree_2 PASSED
tests/t3_fs_api.py::fs_api_tests::test_create PASSED
tests/t3_fs_api.py::fs_api_tests::test_create_open PASSED
tests/t3_fs_api.py::fs_api_tests::test_edit PASSED
tests/t3_fs_api.py::fs_api_tests::test_extstat PASSED
tests/t3_fs_api.py::fs_api_tests::test_failsafe PASSED
tests/t3_fs_api.py::fs_api_tests::test_forget PASSED
tests/t3_fs_api.py::fs_api_tests::test_getattr_root PASSED
tests/t3_fs_api.py::fs_api_tests::test_getxattr PASSED
tests/t3_fs_api.py::fs_api_tests::test_link PASSED
tests/t3_fs_api.py::fs_api_tests::test_listxattr PASSED
tests/t3_fs_api.py::fs_api_tests::test_lock_tree PASSED
tests/t3_fs_api.py::fs_api_tests::test_names PASSED
tests/t3_fs_api.py::fs_api_tests::test_read PASSED
tests/t3_fs_api.py::fs_api_tests::test_readdir PASSED
tests/t3_fs_api.py::fs_api_tests::test_relink PASSED
tests/t3_fs_api.py::fs_api_tests::test_remove_tree PASSED
tests/t3_fs_api.py::fs_api_tests::test_removexattr PASSED
tests/t3_fs_api.py::fs_api_tests::test_rename PASSED
tests/t3_fs_api.py::fs_api_tests::test_replace_dir PASSED
tests/t3_fs_api.py::fs_api_tests::test_replace_file PASSED
tests/t3_fs_api.py::fs_api_tests::test_rmdir PASSED
tests/t3_fs_api.py::fs_api_tests::test_setattr_one PASSED
tests/t3_fs_api.py::fs_api_tests::test_setattr_two PASSED
tests/t3_fs_api.py::fs_api_tests::test_setxattr PASSED
tests/t3_fs_api.py::fs_api_tests::test_statfs PASSED
tests/t3_fs_api.py::fs_api_tests::test_symlink PASSED
tests/t3_fs_api.py::fs_api_tests::test_truncate PASSED
tests/t3_fs_api.py::fs_api_tests::test_truncate_0 PASSED
tests/t3_fs_api.py::fs_api_tests::test_unlink PASSED
tests/t3_fs_api.py::fs_api_tests::test_write PASSED
tests/t3_fsck.py::fsck_tests::test_blocks_checksum PASSED
tests/t3_fsck.py::fsck_tests::test_blocks_obj_id PASSED
tests/t3_fsck.py::fsck_tests::test_cache PASSED
tests/t3_fsck.py::fsck_tests::test_contents_inode PASSED
tests/t3_fsck.py::fsck_tests::test_contents_inode_p PASSED
tests/t3_fsck.py::fsck_tests::test_contents_name PASSED
tests/t3_fsck.py::fsck_tests::test_ext_attrs_inode PASSED
tests/t3_fsck.py::fsck_tests::test_ext_attrs_name PASSED
tests/t3_fsck.py::fsck_tests::test_inode_blocks_block_id PASSED
tests/t3_fsck.py::fsck_tests::test_inode_blocks_inode PASSED
tests/t3_fsck.py::fsck_tests::test_inodes_size PASSED
tests/t3_fsck.py::fsck_tests::test_lof1 PASSED
tests/t3_fsck.py::fsck_tests::test_lof2 PASSED
tests/t3_fsck.py::fsck_tests::test_loops PASSED
tests/t3_fsck.py::fsck_tests::test_missing_obj PASSED
tests/t3_fsck.py::fsck_tests::test_name_refcount PASSED
tests/t3_fsck.py::fsck_tests::test_obj_refcounts PASSED
tests/t3_fsck.py::fsck_tests::test_objects_id PASSED
tests/t3_fsck.py::fsck_tests::test_orphaned_block PASSED
tests/t3_fsck.py::fsck_tests::test_orphaned_inode PASSED
tests/t3_fsck.py::fsck_tests::test_orphaned_name PASSED
tests/t3_fsck.py::fsck_tests::test_orphaned_obj PASSED
tests/t3_fsck.py::fsck_tests::test_symlinks_inode PASSED
tests/t3_fsck.py::fsck_tests::test_tmpfile PASSED
tests/t3_fsck.py::fsck_tests::test_unix_blocks PASSED
tests/t3_fsck.py::fsck_tests::test_unix_child PASSED
tests/t3_fsck.py::fsck_tests::test_unix_nomode_dir PASSED
tests/t3_fsck.py::fsck_tests::test_unix_nomode_reg PASSED
tests/t3_fsck.py::fsck_tests::test_unix_rdev PASSED
tests/t3_fsck.py::fsck_tests::test_unix_size PASSED
tests/t3_fsck.py::fsck_tests::test_unix_size_symlink PASSED
tests/t3_fsck.py::fsck_tests::test_unix_symlink_no_target PASSED
tests/t3_fsck.py::fsck_tests::test_unix_target PASSED
tests/t3_fsck.py::fsck_tests::test_wrong_block_refcount PASSED
tests/t3_fsck.py::fsck_tests::test_wrong_inode_refcount PASSED
tests/t3_inode_cache.py::cache_tests::test_create PASSED
tests/t3_inode_cache.py::cache_tests::test_del PASSED
tests/t3_inode_cache.py::cache_tests::test_get PASSED
tests/t3_verify.py::test_retrieve PASSED
tests/t4_adm.py::AdmTests::test_authinfo PASSED
tests/t4_adm.py::AdmTests::test_passphrase PASSED
tests/t4_fuse.py::TestFuse::test FAILED

=============================================== FAILURES ================================================
_____________________________________________ TestFuse.test _____________________________________________
Traceback (most recent call last):
  File "/root/s3ql/tests/t4_fuse.py", line 166, in test
    self.mount()
  File "/root/s3ql/tests/t4_fuse.py", line 101, in mount
    retry(30, poll)
  File "/root/s3ql/tests/common.py", line 73, in retry
    ret = fn(*a, **kw)
  File "/root/s3ql/tests/t4_fuse.py", line 100, in poll
    assert self.mount_process.poll() is None
AssertionError: assert 1 is None
 +  where 1 = <bound method Popen.poll of <subprocess.Popen object at 0x7fa0332d4080>>()
 +    where <bound method Popen.poll of <subprocess.Popen object at 0x7fa0332d4080>> = <subprocess.Popen object at 0x7fa0332d4080>.poll
 +      where <subprocess.Popen object at 0x7fa0332d4080> = <t4_fuse.TestFuse object at 0x7fa0332d4c18>.mount_process
----------------------------------------- Captured stdout call ------------------------------------------
Please store the following master key in a safe location. It allows 
decryption of the S3QL file system in case the storage objects holding 
this information get corrupted:
---BEGIN MASTER KEY---
QVBg lsan n/TK 1dRK 8wpc 8BEV 8IAx gf18 84+k Z8nG DD4=
---END MASTER KEY---
----------------------------------------- Captured stderr call ------------------------------------------
WARNING: Maximum object sizes less than 1 MiB will degrade performance.
ERROR: Uncaught top-level exception:
Traceback (most recent call last):
  File "/root/s3ql/bin/mount.s3ql", line 26, in <module>
    s3ql.mount.main(sys.argv[1:])
  File "/root/s3ql/src/s3ql/mount.py", line 204, in main
    sd_notify('READY=1')
  File "/usr/local/lib/python3.5/dist-packages/systemd/daemon.py", line 39, in notify
    raise TypeError("state must be an instance of Notigication")
TypeError: state must be an instance of Notigication
=========================================== warnings summary ============================================
t2_block_cache.py::TestBackendPool
  cannot collect test class 'TestBackendPool' because it has a __init__ constructor

-- Docs: http://doc.pytest.org/en/latest/warnings.html
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
===================== 1 failed, 245 passed, 1 skipped, 1 warnings in 97.00 seconds ======================
```

**Comment by leonidasv** [comment]
Solved, not a bug of S3QL B2 Backend: https://bitbucket.org/nikratio/s3ql/issues/251/tests-t4_fusepy-testfuse-test-failed
