### ISSUE TITLE
Error if no prefix

### ISSUE THREAD

**Issue by alanruttenberg** [sylvainlehmann/s3ql#4]
Because then prefix is '' and subsequent check for trailing / tries to access a piece of it

mkfs.s3ql b2://mybucket

    ERROR: Uncaught top-level exception:
    Traceback (most recent call last):
      File "/usr/local/bin/mkfs.s3ql", line 11, in <module>
	load_entry_point('s3ql==2.23', 'console_scripts', 'mkfs.s3ql')()
      File "/usr/local/lib/python3.6/site-packages/s3ql-2.23-py3.6-macosx-10.10-x86_64.egg/s3ql/mkfs.py", line 95, in main
	plain_backend = get_backend(options, raw=True)
      File "/usr/local/lib/python3.6/site-packages/s3ql-2.23-py3.6-macosx-10.10-x86_64.egg/s3ql/common.py", line 260, in get_backend
	getattr(options, 'compress', ('lzma', 2)), raw)()
      File "/usr/local/lib/python3.6/site-packages/s3ql-2.23-py3.6-macosx-10.10-x86_64.egg/s3ql/common.py", line 335, in get_backend_factory
	backend_options)
      File "/usr/local/lib/python3.6/site-packages/s3ql-2.23-py3.6-macosx-10.10-x86_64.egg/s3ql/backends/backblaze.py", line 54, in __init__
	self._parse_storage_url(storage_url)
      File "/usr/local/lib/python3.6/site-packages/s3ql-2.23-py3.6-macosx-10.10-x86_64.egg/s3ql/backends/backblaze.py", line 264, in _parse_storage_url
	prefix = prefix[:-1] if prefix[-1] == '/' else prefix
    IndexError: string index out of range

**Comment by sylvainlehmann** [comment]
Thank you ! This is fixed now.
